#!/usr/bin/env bash
set -e

exec 1> >(logger -s -t $(basename $0)) 2>&1

# Only found useful if linking /var/run/systemd/resolve/resolv.conf
# Fixes issue with systemd-resolved where post VPN connection would leave dns in the wrong order
# Install:
# chown by root
# ln to /etc/NetworkManager/dispatcher.d/zz-systemdresolvfix to run on all NetworkManager events

# Ex args: tun0 vpn-up
arg1="$1"
arg2="$2"

if [[ "${arg2}" =~ "vpn" ]]; then
    echo "VPN operation detected doing systemd-resolved, args $@"
    echo "Before: dump /etc/resolv.conf"
    grep nameserver /etc/resolv.conf
    sleep 3s && systemctl restart systemd-resolved
    echo "After: /etc/resolv.conf"
    grep nameserver /etc/resolv.conf
    echo "Finishing $0"
fi
